# Generated by Django 5.1.1 on 2026-04-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_calendarevent_courseprogress_learninghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='student_class',
            field=models.CharField(default='Class 10', max_length=50),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='student.student'),
        ),
    ]
