# Generated by Django 5.2.12 on 2026-03-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_mobile', models.CharField(max_length=100)),
                ('department_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_id', models.CharField(max_length=100)),
                ('subject_department', models.CharField(max_length=100)),
                ('subject_image', models.ImageField(blank=True, upload_to='teachers/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.department')),
            ],
        ),
    ]
