# Generated by Django 5.2.12 on 2026-03-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_mobile',
        ),
    ]
