# Generated by Django 5.2.12 on 2026-03-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=100)),
                ('hod_mobile', models.CharField(max_length=100)),
                ('hod_email', models.EmailField(max_length=100)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=100)),
                ('department_email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('ction', models.CharField(max_length=100)),
                ('department_image', models.ImageField(blank=True, upload_to='departments/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.hod')),
            ],
        ),
    ]
