# Generated by Django 5.1.1 on 2026-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8ZvJH0qN5x06FfF39ykzQZo10aBJlQgK', editable=False, max_length=32, unique=True),
        ),
    ]
