# Generated by Django 5.1.1 on 2026-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='DWM7Ny6DW0zIgKn3QGHtiF1pEGnQ5iMW', editable=False, max_length=32, unique=True),
        ),
    ]
