# Generated by Django 5.1.1 on 2026-03-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NCT5SpoLKHZb4wwCPckmIh7c2MoLRH3W', editable=False, max_length=32, unique=True),
        ),
    ]
