# Generated by Django 5.1.1 on 2026-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yRLszSUOwfbx5fpu6O8j1bEYxS3nOUrT', editable=False, max_length=32, unique=True),
        ),
    ]
