# Generated by Django 5.1.1 on 2026-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ggpxMsIX8cckfVfg6mja5zv6YJvYtMlK', editable=False, max_length=32, unique=True),
        ),
    ]
