# Generated by Django 5.1.1 on 2026-03-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vCXQAhSggy7yLGRg15J02FH7qOAixmAM', editable=False, max_length=32, unique=True),
        ),
    ]
