# Generated by Django 5.1 on 2026-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ivOBcN3CB7ozdnQ2mTtzJfjIOVtSq5kR', editable=False, max_length=32, unique=True),
        ),
    ]
