# Generated by Django 5.1.1 on 2026-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vrDm1RmA6zkRoNQ2hYjJ6YZb5doBhhNS', editable=False, max_length=32, unique=True),
        ),
    ]
